Correct the timing of emit_object_added
ibm-openbmc/phosphor-debug-collector pull request #117
Opened 2023-08-03 07:06 UTC by deepakala-k

The deletion of the dump objects emits InterfacesRemoved signal, but the interfaces removed in the signal does not contain the interfaces defined in the base class phosphor::dump::Entry:
```
xyz.openbmc_project.Common.OriginatedBy
xyz.openbmc_project.Common.Progress
xyz.openbmc_project.Dump.Entry
xyz.openbmc_project.Object.Delete
xyz.openbmc_project.Time.EpochTime
```

This results in the mapper still keeping the objects even if the object is removed from DBus, and it becomes inconsistent between the DBus objects and mapper.

Adjust the inheritance sequence, so that in destruction, emit_object_removed() is called when all the interfaces are there, so that all the interfaces could be included in the signal.

Without this change, the destructor sequence is (Taking BMCEntry as example):
1. phosphor::dump::Entry is destructed, no signal is emitted;
2. phosphor::dump::bmc::EntryIfaces is destructed, signal is emitted, but at this time, only the interfaces implemented by phosphor::dump::bmc::EntryIfaces is included, which is the root cause of the below problem.

Delete of Resource dump causes Phosphor log manager to look for resource/entry/1 by default

With the change, the destructor sequence is:
1. phosphor::dump::bmc::EntryIfaces is destructed, signal is emitted, and all the interfaces are included in the signal;
2. phosphor::dump::Entry is destructed, no signal is emitted.

So all the interfaces implemented by BMCEntry is included in the InterfacesRemoved signal, and thus the issue is fixed.

Tested: Before this change:
        1. Create a dump, say /xyz/openbmc_project/dump/bmc/entry/2
        2. Delete it
        3. Mapper still list the above object although it does not
        really exist.
        With this fix, verify the above issue is fixed.

2023-08-03 12:34 UTC, dhruvibm requested changes
Need change in hostdump too

2023-08-03 12:39 UTC, deepakala-k commented
> Need change in hostdump too

Sure. Will address it. Thank you!

2023-08-04 10:15 UTC, devenrao approved these changes

2023-08-07 09:29 UTC, dhruvibm approved these changes

2023-08-07 13:56 UTC, dhruvibm requested changes
The change in the bmcstored_entry is not a separate commit, please keep it with the same commit

2023-08-08 04:59 UTC, deepakala-k commented
> The change in the bmcstored_entry is not a separate commit, please keep it with the same commit

Sure. Though in the first commit, we are ONLY changing the order in which they are inherited and the other commit adds extra parameter to the base constructor, I can squash them into single commit.

2023-08-08 10:48 UTC, dhruvibm approved these changes

2023-08-09 01:04 UTC, geissonator commented
add to approvelist

2023-08-09 15:18 UTC, merged